version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio_app
    ports:
      - "3001:3000"   # map port 3000 inside container → port 3001 on host
    restart: always
    environment:
      - NODE_ENV=production
